// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU7APnZo8uwW2E7Ujx1JhgdbS_1HMvuJc',
    appId: '1:173588335327:web:325d14a34079a74fbd376a',
    messagingSenderId: '173588335327',
    projectId: 'laufen-app',
    authDomain: 'laufen-app.firebaseapp.com',
    storageBucket: 'laufen-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtj7DcsJQ03eyXX6jdCYrqd4k5oR-cir0',
    appId: '1:173588335327:android:fce39876e2ad88dfbd376a',
    messagingSenderId: '173588335327',
    projectId: 'laufen-app',
    storageBucket: 'laufen-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJQH4_S-LAg5Un11S5YJQvHxDGMzl3skk',
    appId: '1:173588335327:ios:d4f110bea887d0d2bd376a',
    messagingSenderId: '173588335327',
    projectId: 'laufen-app',
    storageBucket: 'laufen-app.firebasestorage.app',
    iosClientId: '173588335327-r54fielp4tkqfbs1hobfa8t2i84ksvmf.apps.googleusercontent.com',
    iosBundleId: 'com.laufen.laufen',
  );
}
